### ISSUE TITLE
Forward connection(s) property

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/sckan-composer#154]
User Story: A circuit is created from multiple connection statements. When composing statements, I would like to designate the statement that describes the next part of the path.

Acceptance Criteria: Create a forward connection property which specifies the unique identifier for an existing statement. This forward connection has the following predicate to be stored in the data table and made available for export, “hasForwardConnection” The distillation role and curator role will see this property in proofing tab as a separate field below the Path. In a given sentence, a statement’s forward connection field will offer the other statements’ unique identifiers that have been created from the same sentence. An option to search for forward connections will launch a search for neuron populations that have an ORIGIN = the DESTINATION of the selected statement.

**Comment by stappan** [comment]
This is a high priority, and we need to be able to easily find and include the statement. We currently do this by noting the unique identifier (which is why Ilias is keen to have this field highly visible)

[note to self: ask Maryann and Ilias and Tom and Fahim if we need to review connected statements after a change is made to the current statement]
