### ISSUE TITLE
[Feature request] Graph sorting with afferent terminal

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/sckan-composer#314]
Acceptance criteria: if destination is afferent terminal move it to the top of the graph, so vertically we will see afferent terminal (destinations), the vias that lead to it and the origins.

**Comment by stappan** [comment]
here is a few statements that include both afferent and axon terminals: https://composer.scicrunch.io/statement/246

https://composer.scicrunch.io/statement/184

**Comment by stappan** [comment]
@ddelpiano has this been worked on? I seem to recall that the design Salam did included this?

**Comment by ddelpiano** [comment]
This should apply only to afferent terminal, the other destinations should stay at the bottom.

**Comment by stappan** [comment]
Sprint 21 & Sprint 22

**Comment by stappan** [comment]
> Acceptance criteria: if destination is afferent terminal move it to the top of the graph, so vertically we will see afferent terminal (destinations), the vias that lead to it and the origins.

@ddelpiano the Acceptance criteria should allow: 
![image](https://github.com/user-attachments/assets/02df36b5-f61a-4dae-8ac4-027e069534af)
 to be ordered like this from top to bottom:  
 afferent terminal destinations -> afferent terminal's vias -> origin -> axon terminal vias -> axon terminal destinations

**Comment by ddelpiano** [comment]
@stappan this is on hold waiting for some more info here https://metacell.slack.com/archives/C0477SPSQQK/p1731672320880049

**Comment by stappan** [comment]
@ddelpiano 
the development to draw the graph when axon sensory terminal is specified, the graph should be drawn in this order: sensory terminal(s) --> vias --> soma --> vias --> axon terminal. 

if the vias are shared, do nothing. Graph could/will look goofy. Curator must manually fix by adjusting vias, and/or locking the drawing of the graph.

**Comment by stappan** [comment]
**Acceptance criteria:**

- the afferent terminal widget is changed to have an Sending port rather than a Receiving one.
- the graph will be traversed from the afferent terminal to the soma/origin in order to flip the connections from/to, since the afferent terminal will have to go at the top.
- We will continue then to draw the graph from origin to axon terminal, being careful in not repeating connections that already exists/might have been draw already in the steps above to connect the afferent terminal
- the Soma/origin will need to have a receiving and sending port, since it's receiving from the Afferent terminal (and it's vias) and sending out to the Axon Terminal.
- From the styling point of view, the edges won't have any head/arrow and the ports will collide at the center of each widget, so you won't see any difference in a connection that goes from/to or to/from the same nodes.
- Edges connecting vertically aligned objects will have 0/180 degree angle line (i.e., straight up and down, not off angle).

User Story: Smart routing will draw the graph starting from the afferent terminal and finishing at the axon terminal when at least one of each are present. If no afferent endings (axon sensory terminal) exist, graph starts with origins to axon terminals.

**Comment by stappan** [comment]
@ddelpiano added acceptance criteria from slack convo https://scicrunch.slack.com/archives/C0477SPSQQK/p1732130306037909?thread_ts=1731672320.880049&cid=C0477SPSQQK here, 

and added the vertical alignment.

**Comment by iliasziogas** [comment]
@stappan should we add here in the acceptance criteria that: 

- in sensory populations when the "via" going to "axon terminal" is the same with the "via" going to the "axon sensory terminal" then show the record as Invalid and demonstrate the message: __Record invalid because "axon terminal" and "axon sensory terminal" have the same "via"_._

**Comment by stappan** [comment]
@ddelpiano , with respect "To discuss what to do with incomplete graphs, for now we are displaying the nodes in the graph canvas to save computation time."

- I agree - nodes should be present on the graph, and not connected  if you don't know where to put them.

**Comment by ddelpiano** [comment]
Released with 3.2.0
