### ISSUE TITLE
[feature] segregate automatic "system user" notes from curator notes in Knowledge statements and sentences

### ISSUE THREAD

**Issue by stappan** [MetaCell/sckan-composer#321]
there is too much noise provided by the system state machine in the Notes section, which makes it difficult to see comments that need to be acted upon. 

It would be helpful to by default filter out all "system user notes" state machine changes EXCEPT: Exported and Invalid; since these states provide useful information about the statement/sentence.

Acceptance Criteria:
-by default, show human-created notes & those associated with Invalid and Exported states.
-enable a "show system details" check box to toggle the full display for an individual statement/sentence

**Comment by ddelpiano** [comment]
@stappan 

> -do we/should we need an admin version of this that allows you to do something relevant across many/all statements/sentences?

Do you want the admin version because you want  to persist the state of this option in the database?
Meaning, I am visiting statement XYZ, as requested by default we show only the human notes and those that contains an update about invalid or exported states. I use the toggle/checkbox to show system details.
I then move to another statement ABC, still following the default behaviour for the notes, I do my work and then go back to XYZ. Should XYZ still display the system details notes or every time we visit a record we use the defaul behaviour?

Could you please assess the priority of this? thanks

**Comment by stappan** [comment]
@ddelpiano after further discussion, we don't need the admin version for that. It would be good to know how many statements/sentences have a given system message (e.g., missing axiom, missing destination etc;) but i think this is a lower priority (and likely would be separate from this ask anyway. I think it should be moved to it's own request. 

So, Acceptance Criteria:
-by default, show human-created notes & those associated with Invalid and Exported states.
-enable a "show system details" check box to toggle the full display for an individual statement/sentence

Can you please provide the effort estimate? That will help determine priority.

**Comment by ddelpiano** [comment]
between 3 and 6 hours, just because we don't have a design yet, but if it's a simple checkbox in the current UI, it should be 3-4 hours.

**Comment by stappan** [comment]
@ddelpiano excellent - checkbox it is! let's do this with this sprint please.

**Comment by stappan** [comment]
in Sprint 22

**Comment by stappan** [comment]
@iliasziogas I consider this item tested, it works great for me on staging. Please test, and raise an alert here if you see anything that needs adjustment. [https://composer.sckan.stage.metacell.us/statement/82](url)
